services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here
      - key: WEBHOOK_SECRET
        value: valid-secret-123-ABC_xyz  # This will work
      - key: PYTHON_VERSION
        value: 3.9.7
